### ISSUE TITLE
Kubernetes config

### ISSUE THREAD

**Issue by fire** [linuxserver/docker-quassel-core#15]
Tested on Google container engine. Supports Postgresql, but you'll have to setup another Statefulset for that.

```yml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: quassel
spec:
  serviceName: "quassel"
  replicas: 1
  template:
    metadata:
      labels:
        app: quassel
      annotations:
    spec:
      containers:
      - name: quassel
        image: linuxserver/quassel-core
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4242
          name: quassel
        livenessProbe:
          tcpSocket:
            port: 4242
          initialDelaySeconds: 180
        readinessProbe:
          tcpSocket:
            port: 4242
          initialDelaySeconds: 10
        volumeMounts:
        - name: configdir
          mountPath: /config
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: configdir
  volumeClaimTemplates:
  - metadata:
      name: configdir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of quassel.
  name: quassel-public
  labels:
    app: quassel
spec:
  ports:
  # Quassel Client
  - port: 4242
    targetPort: 4242
    name: quassel
  selector:
    app: quassel
  type: LoadBalancer
```
